language: ruby
gemfile: gemfiles/ruby-others
script: bundle exec rake $TASK
env:
  - TASK=test
matrix:
  include:
    - rvm: 1.9
      gemfile: gemfiles/ruby-1.9
    - rvm: 2.0
      gemfile: gemfiles/ruby-2.0
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - env: TASK=rubocop
      rvm: 2.3
